export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET"

export const FETCH_ORDER_DETAILS_REQUEST = "FETCH_ORDER_DETAILS_REQUEST"
export const FETCH_ORDER_DETAILS_SUCCESS ="FETCH_ORDER_DETAILS_SUCCESS"
export const FETCH_ORDER_DETAILS_FAIL = "FETCH_ORDER_DETAILS_FAIL"